import { Course, Batch, Category } from '@/types'
import { getTomorrowDate } from './utils'

export const categories: Category[] = [
  {
    id: 'web-dev',
    name: 'Web Development',
    description: 'Master modern web technologies and frameworks',
    icon: '🌐',
    color: 'from-blue-500 to-cyan-500',
    courseCount: 10,
  },
  {
    id: 'ai-ml',
    name: 'AI & Machine Learning',
    description: 'Deep learning, neural networks, and AI applications',
    icon: '🤖',
    color: 'from-violet-500 to-purple-500',
    courseCount: 6,
  },
  {
    id: 'data-science',
    name: 'Data Science',
    description: 'Data analysis, ML, and AI expertise',
    icon: '📊',
    color: 'from-purple-500 to-pink-500',
    courseCount: 5,
  },
  {
    id: 'cloud',
    name: 'Cloud Computing',
    description: 'AWS, Azure, GCP cloud platforms',
    icon: '☁️',
    color: 'from-orange-500 to-red-500',
    courseCount: 4,
  },
  {
    id: 'devops',
    name: 'DevOps',
    description: 'CI/CD, Docker, Kubernetes, and cloud infrastructure',
    icon: '⚙️',
    color: 'from-green-500 to-emerald-500',
    courseCount: 4,
  },
  {
    id: 'mobile',
    name: 'Mobile Development',
    description: 'iOS, Android, React Native, Flutter',
    icon: '📱',
    color: 'from-indigo-500 to-purple-500',
    courseCount: 3,
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity',
    description: 'Ethical hacking, security protocols, and defense',
    icon: '🔒',
    color: 'from-red-500 to-orange-500',
    courseCount: 3,
  },
  {
    id: 'blockchain',
    name: 'Blockchain & Web3',
    description: 'Smart contracts, Web3, and decentralized apps',
    icon: '⛓️',
    color: 'from-yellow-500 to-amber-500',
    courseCount: 2,
  },
]

export const courses: Course[] = [
  {
    id: 'nextjs-fullstack',
    title: 'Next.js 15 Full Stack Development',
    description: 'Master Next.js 15, React Server Components, App Router, and build production-ready full-stack applications',
    category: 'web-dev',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Intermediate',
    price: 18999,
    image: '/api/placeholder/400/250',
    rating: 4.9,
    studentsCount: 3200,
    lessons: 45,
    tags: ['Next.js 15', 'React', 'TypeScript', 'Full Stack', 'App Router'],
  },
  {
    id: 'fullstack-mern',
    title: 'MERN Stack Development',
    description: 'Complete full-stack development with MongoDB, Express, React, and Node.js. Build real-world applications',
    category: 'web-dev',
    instructor: 'Aditya Bhardwaj',
    duration: '12 weeks',
    level: 'Intermediate',
    price: 16999,
    image: '/api/placeholder/400/250',
    rating: 4.8,
    studentsCount: 4500,
    lessons: 50,
    tags: ['MongoDB', 'Express', 'React', 'Node.js', 'MERN'],
  },
  {
    id: 'ai-ml-python',
    title: 'AI & Machine Learning with Python',
    description: 'Master AI/ML fundamentals, neural networks, TensorFlow, PyTorch, and build intelligent applications',
    category: 'ai-ml',
    instructor: 'Aditya Bhardwaj',
    duration: '14 weeks',
    level: 'Advanced',
    price: 24999,
    image: '/api/placeholder/400/250',
    rating: 4.9,
    studentsCount: 2800,
    lessons: 60,
    tags: ['Python', 'TensorFlow', 'PyTorch', 'Neural Networks', 'AI'],
  },
  {
    id: 'data-science-python',
    title: 'Data Science with Python',
    description: 'Complete data science bootcamp: pandas, numpy, scikit-learn, data visualization, and machine learning',
    category: 'data-science',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Beginner',
    price: 12999,
    image: '/api/placeholder/400/250',
    rating: 4.8,
    studentsCount: 5200,
    lessons: 42,
    tags: ['Python', 'Pandas', 'NumPy', 'Matplotlib', 'Data Science'],
  },
  {
    id: 'aws-cloud',
    title: 'AWS Cloud Solutions Architect',
    description: 'Master AWS services, cloud architecture, and prepare for AWS Solutions Architect certification',
    category: 'cloud',
    instructor: 'Aditya Bhardwaj',
    duration: '8 weeks',
    level: 'Advanced',
    price: 21999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 1800,
    lessons: 35,
    tags: ['AWS', 'Cloud', 'DevOps', 'Infrastructure', 'Certification'],
  },
  {
    id: 'azure-cloud',
    title: 'Microsoft Azure Cloud Fundamentals',
    description: 'Learn Azure services, cloud computing, and prepare for Azure certification exams',
    category: 'cloud',
    instructor: 'Aditya Bhardwaj',
    duration: '8 weeks',
    level: 'Beginner',
    price: 14999,
    image: '/api/placeholder/400/250',
    rating: 4.6,
    studentsCount: 2100,
    lessons: 32,
    tags: ['Azure', 'Cloud', 'Microsoft', 'Infrastructure'],
  },
  {
    id: 'docker-kubernetes',
    title: 'Docker & Kubernetes Mastery',
    description: 'Containerization, orchestration, CI/CD pipelines, and DevOps best practices',
    category: 'devops',
    instructor: 'Aditya Bhardwaj',
    duration: '6 weeks',
    level: 'Intermediate',
    price: 15999,
    image: '/api/placeholder/400/250',
    rating: 4.8,
    studentsCount: 2400,
    lessons: 28,
    tags: ['Docker', 'Kubernetes', 'CI/CD', 'DevOps', 'Containers'],
  },
  {
    id: 'react-native',
    title: 'React Native Mobile Development',
    description: 'Build cross-platform mobile apps for iOS and Android using React Native',
    category: 'mobile',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Intermediate',
    price: 17999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 1900,
    lessons: 40,
    tags: ['React Native', 'Mobile', 'iOS', 'Android', 'Cross-platform'],
  },
  {
    id: 'ethical-hacking',
    title: 'Ethical Hacking & Cybersecurity',
    description: 'Learn ethical hacking, penetration testing, security protocols, and cybersecurity defense',
    category: 'cybersecurity',
    instructor: 'Aditya Bhardwaj',
    duration: '14 weeks',
    level: 'Advanced',
    price: 22999,
    image: '/api/placeholder/400/250',
    rating: 4.9,
    studentsCount: 1500,
    lessons: 55,
    tags: ['Security', 'Penetration Testing', 'Kali Linux', 'Ethical Hacking', 'Cybersecurity'],
  },
  {
    id: 'blockchain-web3',
    title: 'Blockchain & Web3 Development',
    description: 'Build decentralized applications with Solidity, Ethereum, smart contracts, and Web3 technologies',
    category: 'blockchain',
    instructor: 'Aditya Bhardwaj',
    duration: '12 weeks',
    level: 'Intermediate',
    price: 19999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 1200,
    lessons: 48,
    tags: ['Blockchain', 'Solidity', 'Ethereum', 'Web3', 'Smart Contracts'],
  },
  {
    id: 'react-advanced',
    title: 'Advanced React Development',
    description: 'Master advanced React patterns, hooks, performance optimization, and state management',
    category: 'web-dev',
    instructor: 'Aditya Bhardwaj',
    duration: '8 weeks',
    level: 'Advanced',
    price: 14999,
    image: '/api/placeholder/400/250',
    rating: 4.9,
    studentsCount: 3800,
    lessons: 35,
    tags: ['React', 'Hooks', 'Performance', 'State Management', 'Advanced'],
  },
  {
    id: 'nodejs-backend',
    title: 'Node.js Backend Development',
    description: 'Build scalable backend APIs with Node.js, Express, RESTful services, and database integration',
    category: 'web-dev',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Intermediate',
    price: 13999,
    image: '/api/placeholder/400/250',
    rating: 4.8,
    studentsCount: 2900,
    lessons: 38,
    tags: ['Node.js', 'Express', 'API', 'Backend', 'REST'],
  },
  {
    id: 'typescript-mastery',
    title: 'TypeScript Mastery',
    description: 'Master TypeScript for modern web development, type safety, and advanced patterns',
    category: 'web-dev',
    instructor: 'Aditya Bhardwaj',
    duration: '6 weeks',
    level: 'Intermediate',
    price: 9999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 2200,
    lessons: 25,
    tags: ['TypeScript', 'Type Safety', 'JavaScript', 'Advanced'],
  },
  {
    id: 'devops-aws',
    title: 'DevOps with AWS',
    description: 'CI/CD pipelines, infrastructure as code, monitoring, and DevOps best practices on AWS',
    category: 'devops',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Advanced',
    price: 19999,
    image: '/api/placeholder/400/250',
    rating: 4.8,
    studentsCount: 1600,
    lessons: 42,
    tags: ['DevOps', 'AWS', 'CI/CD', 'Infrastructure', 'Automation'],
  },
  {
    id: 'flutter-mobile',
    title: 'Flutter Mobile Development',
    description: 'Build beautiful cross-platform mobile apps with Flutter and Dart',
    category: 'mobile',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Intermediate',
    price: 16999,
    image: '/api/placeholder/400/250',
    rating: 4.6,
    studentsCount: 1400,
    lessons: 40,
    tags: ['Flutter', 'Dart', 'Mobile', 'Cross-platform'],
  },
  {
    id: 'python-automation',
    title: 'Python for Automation & Scripting',
    description: 'Learn Python for automation, web scraping, API development, and scripting',
    category: 'web-dev',
    instructor: 'Aditya Bhardwaj',
    duration: '8 weeks',
    level: 'Beginner',
    price: 8999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 3500,
    lessons: 30,
    tags: ['Python', 'Automation', 'Scripting', 'Web Scraping'],
  },
  {
    id: 'cybersecurity-fundamentals',
    title: 'Cybersecurity Fundamentals',
    description: 'Learn cybersecurity basics, network security, encryption, and security best practices',
    category: 'cybersecurity',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Beginner',
    price: 14999,
    image: '/api/placeholder/400/250',
    rating: 4.6,
    studentsCount: 1800,
    lessons: 38,
    tags: ['Cybersecurity', 'Network Security', 'Encryption', 'Security'],
  },
  {
    id: 'data-analytics',
    title: 'Data Analytics with SQL & Python',
    description: 'Master data analytics, SQL queries, data visualization, and business intelligence',
    category: 'data-science',
    instructor: 'Aditya Bhardwaj',
    duration: '8 weeks',
    level: 'Beginner',
    price: 11999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 2600,
    lessons: 32,
    tags: ['SQL', 'Python', 'Data Analytics', 'Business Intelligence'],
  },
  {
    id: 'gcp-cloud',
    title: 'Google Cloud Platform (GCP)',
    description: 'Master GCP services, cloud architecture, and prepare for GCP certification',
    category: 'cloud',
    instructor: 'Aditya Bhardwaj',
    duration: '8 weeks',
    level: 'Intermediate',
    price: 18999,
    image: '/api/placeholder/400/250',
    rating: 4.6,
    studentsCount: 1100,
    lessons: 35,
    tags: ['GCP', 'Google Cloud', 'Cloud', 'Infrastructure'],
  },
  {
    id: 'jenkins-cicd',
    title: 'CI/CD with Jenkins & GitLab',
    description: 'Master continuous integration and deployment with Jenkins, GitLab CI, and automation',
    category: 'devops',
    instructor: 'Aditya Bhardwaj',
    duration: '6 weeks',
    level: 'Intermediate',
    price: 12999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 1300,
    lessons: 26,
    tags: ['Jenkins', 'CI/CD', 'GitLab', 'Automation', 'DevOps'],
  },
  {
    id: 'web3-defi',
    title: 'Web3 & DeFi Development',
    description: 'Build decentralized finance applications, smart contracts, and Web3 dApps',
    category: 'blockchain',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Advanced',
    price: 22999,
    image: '/api/placeholder/400/250',
    rating: 4.8,
    studentsCount: 800,
    lessons: 42,
    tags: ['Web3', 'DeFi', 'Blockchain', 'Smart Contracts', 'dApps'],
  },
]

// Get tomorrow's date for all batch start dates
const tomorrowDate = getTomorrowDate()

export const batches: Batch[] = [
  {
    id: 'batch-001',
    courseId: 'nextjs-fullstack',
    name: 'Next.js 15 Full Stack - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Mon, Wed, Fri - 7:00 PM IST',
    capacity: 50,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-002',
    courseId: 'fullstack-mern',
    name: 'MERN Stack - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-05-02', // 12 weeks
    schedule: 'Tue, Thu - 6:00 PM IST',
    capacity: 40,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-003',
    courseId: 'ai-ml-python',
    name: 'AI & ML with Python - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-05-15', // 14 weeks
    schedule: 'Mon, Wed, Fri - 8:00 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-004',
    courseId: 'data-science-python',
    name: 'Data Science - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Sat, Sun - 10:00 AM IST',
    capacity: 35,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-005',
    courseId: 'aws-cloud',
    name: 'AWS Solutions Architect - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-05', // 8 weeks
    schedule: 'Mon, Wed, Fri - 7:30 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-006',
    courseId: 'docker-kubernetes',
    name: 'Docker & Kubernetes - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-03-22', // 6 weeks
    schedule: 'Tue, Thu - 7:00 PM IST',
    capacity: 35,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-007',
    courseId: 'react-native',
    name: 'React Native - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Mon, Wed, Fri - 6:30 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-008',
    courseId: 'ethical-hacking',
    name: 'Ethical Hacking - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-05-15', // 14 weeks
    schedule: 'Sat, Sun - 2:00 PM IST',
    capacity: 25,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-009',
    courseId: 'blockchain-web3',
    name: 'Blockchain & Web3 - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-05-02', // 12 weeks
    schedule: 'Tue, Thu - 8:00 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-010',
    courseId: 'react-advanced',
    name: 'Advanced React - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-05', // 8 weeks
    schedule: 'Mon, Wed, Fri - 6:00 PM IST',
    capacity: 40,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-011',
    courseId: 'azure-cloud',
    name: 'Microsoft Azure - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-05', // 8 weeks
    schedule: 'Tue, Thu - 7:00 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-012',
    courseId: 'nodejs-backend',
    name: 'Node.js Backend - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Mon, Wed, Fri - 6:30 PM IST',
    capacity: 40,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-013',
    courseId: 'typescript-mastery',
    name: 'TypeScript Mastery - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-03-22', // 6 weeks
    schedule: 'Sat, Sun - 11:00 AM IST',
    capacity: 35,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-014',
    courseId: 'devops-aws',
    name: 'DevOps with AWS - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Mon, Wed, Fri - 8:00 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-015',
    courseId: 'flutter-mobile',
    name: 'Flutter Mobile - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Tue, Thu - 7:30 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-016',
    courseId: 'python-automation',
    name: 'Python Automation - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-05', // 8 weeks
    schedule: 'Mon, Wed, Fri - 7:00 PM IST',
    capacity: 40,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-017',
    courseId: 'cybersecurity-fundamentals',
    name: 'Cybersecurity Fundamentals - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Sat, Sun - 1:00 PM IST',
    capacity: 35,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-018',
    courseId: 'data-analytics',
    name: 'Data Analytics - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-05', // 8 weeks
    schedule: 'Mon, Wed, Fri - 6:00 PM IST',
    capacity: 35,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-019',
    courseId: 'gcp-cloud',
    name: 'Google Cloud Platform - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-05', // 8 weeks
    schedule: 'Tue, Thu - 8:00 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-020',
    courseId: 'jenkins-cicd',
    name: 'CI/CD with Jenkins - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-03-22', // 6 weeks
    schedule: 'Sat, Sun - 10:00 AM IST',
    capacity: 35,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-021',
    courseId: 'web3-defi',
    name: 'Web3 & DeFi - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Tue, Thu - 7:00 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
]
