import { Course, Batch, Category, Product } from '@/types'
import { getTomorrowDate } from './utils'

export const categories: Category[] = [
  {
    id: 'web-dev',
    name: 'Web Development',
    description: 'Master modern web technologies and frameworks',
    icon: '🌐',
    color: 'from-blue-500 to-cyan-500',
    courseCount: 10,
  },
  {
    id: 'ai-ml',
    name: 'AI & Machine Learning',
    description: 'Deep learning, neural networks, and AI applications',
    icon: '🤖',
    color: 'from-violet-500 to-purple-500',
    courseCount: 6,
  },
  {
    id: 'data-science',
    name: 'Data Science',
    description: 'Data analysis, ML, and AI expertise',
    icon: '📊',
    color: 'from-purple-500 to-pink-500',
    courseCount: 5,
  },
  {
    id: 'cloud',
    name: 'Cloud Computing',
    description: 'AWS, Azure, GCP cloud platforms',
    icon: '☁️',
    color: 'from-orange-500 to-red-500',
    courseCount: 4,
  },
  {
    id: 'devops',
    name: 'DevOps',
    description: 'CI/CD, Docker, Kubernetes, and cloud infrastructure',
    icon: '⚙️',
    color: 'from-green-500 to-emerald-500',
    courseCount: 4,
  },
  {
    id: 'mobile',
    name: 'Mobile Development',
    description: 'iOS, Android, React Native, Flutter',
    icon: '📱',
    color: 'from-indigo-500 to-purple-500',
    courseCount: 3,
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity',
    description: 'Ethical hacking, security protocols, and defense',
    icon: '🔒',
    color: 'from-red-500 to-orange-500',
    courseCount: 3,
  },
  {
    id: 'blockchain',
    name: 'Blockchain & Web3',
    description: 'Smart contracts, Web3, and decentralized apps',
    icon: '⛓️',
    color: 'from-yellow-500 to-amber-500',
    courseCount: 2,
  },
]

export const courses: Course[] = [
  {
    id: 'nextjs-fullstack',
    title: 'Next.js 15 Full Stack Development',
    description: 'Master Next.js 15, React Server Components, App Router, and build production-ready full-stack applications',
    category: 'web-dev',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Intermediate',
    price: 18999,
    image: '/api/placeholder/400/250',
    rating: 4.9,
    studentsCount: 3200,
    lessons: 45,
    tags: ['Next.js 15', 'React', 'TypeScript', 'Full Stack', 'App Router'],
  },
  {
    id: 'fullstack-mern',
    title: 'MERN Stack Development',
    description: 'Complete full-stack development with MongoDB, Express, React, and Node.js. Build real-world applications',
    category: 'web-dev',
    instructor: 'Aditya Bhardwaj',
    duration: '12 weeks',
    level: 'Intermediate',
    price: 16999,
    image: '/api/placeholder/400/250',
    rating: 4.8,
    studentsCount: 4500,
    lessons: 50,
    tags: ['MongoDB', 'Express', 'React', 'Node.js', 'MERN'],
  },
  {
    id: 'ai-ml-python',
    title: 'AI & Machine Learning with Python',
    description: 'Master AI/ML fundamentals, neural networks, TensorFlow, PyTorch, and build intelligent applications',
    category: 'ai-ml',
    instructor: 'Aditya Bhardwaj',
    duration: '14 weeks',
    level: 'Advanced',
    price: 24999,
    image: '/api/placeholder/400/250',
    rating: 4.9,
    studentsCount: 2800,
    lessons: 60,
    tags: ['Python', 'TensorFlow', 'PyTorch', 'Neural Networks', 'AI'],
  },
  {
    id: 'data-science-python',
    title: 'Data Science with Python',
    description: 'Complete data science bootcamp: pandas, numpy, scikit-learn, data visualization, and machine learning',
    category: 'data-science',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Beginner',
    price: 12999,
    image: '/api/placeholder/400/250',
    rating: 4.8,
    studentsCount: 5200,
    lessons: 42,
    tags: ['Python', 'Pandas', 'NumPy', 'Matplotlib', 'Data Science'],
  },
  {
    id: 'aws-cloud',
    title: 'AWS Cloud Solutions Architect',
    description: 'Master AWS services, cloud architecture, and prepare for AWS Solutions Architect certification',
    category: 'cloud',
    instructor: 'Aditya Bhardwaj',
    duration: '8 weeks',
    level: 'Advanced',
    price: 21999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 1800,
    lessons: 35,
    tags: ['AWS', 'Cloud', 'DevOps', 'Infrastructure', 'Certification'],
  },
  {
    id: 'azure-cloud',
    title: 'Microsoft Azure Cloud Fundamentals',
    description: 'Learn Azure services, cloud computing, and prepare for Azure certification exams',
    category: 'cloud',
    instructor: 'Aditya Bhardwaj',
    duration: '8 weeks',
    level: 'Beginner',
    price: 14999,
    image: '/api/placeholder/400/250',
    rating: 4.6,
    studentsCount: 2100,
    lessons: 32,
    tags: ['Azure', 'Cloud', 'Microsoft', 'Infrastructure'],
  },
  {
    id: 'docker-kubernetes',
    title: 'Docker & Kubernetes Mastery',
    description: 'Containerization, orchestration, CI/CD pipelines, and DevOps best practices',
    category: 'devops',
    instructor: 'Aditya Bhardwaj',
    duration: '6 weeks',
    level: 'Intermediate',
    price: 15999,
    image: '/api/placeholder/400/250',
    rating: 4.8,
    studentsCount: 2400,
    lessons: 28,
    tags: ['Docker', 'Kubernetes', 'CI/CD', 'DevOps', 'Containers'],
  },
  {
    id: 'react-native',
    title: 'React Native Mobile Development',
    description: 'Build cross-platform mobile apps for iOS and Android using React Native',
    category: 'mobile',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Intermediate',
    price: 17999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 1900,
    lessons: 40,
    tags: ['React Native', 'Mobile', 'iOS', 'Android', 'Cross-platform'],
  },
  {
    id: 'ethical-hacking',
    title: 'Ethical Hacking & Cybersecurity',
    description: 'Learn ethical hacking, penetration testing, security protocols, and cybersecurity defense',
    category: 'cybersecurity',
    instructor: 'Aditya Bhardwaj',
    duration: '14 weeks',
    level: 'Advanced',
    price: 22999,
    image: '/api/placeholder/400/250',
    rating: 4.9,
    studentsCount: 1500,
    lessons: 55,
    tags: ['Security', 'Penetration Testing', 'Kali Linux', 'Ethical Hacking', 'Cybersecurity'],
  },
  {
    id: 'blockchain-web3',
    title: 'Blockchain & Web3 Development',
    description: 'Build decentralized applications with Solidity, Ethereum, smart contracts, and Web3 technologies',
    category: 'blockchain',
    instructor: 'Aditya Bhardwaj',
    duration: '12 weeks',
    level: 'Intermediate',
    price: 19999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 1200,
    lessons: 48,
    tags: ['Blockchain', 'Solidity', 'Ethereum', 'Web3', 'Smart Contracts'],
  },
  {
    id: 'react-advanced',
    title: 'Advanced React Development',
    description: 'Master advanced React patterns, hooks, performance optimization, and state management',
    category: 'web-dev',
    instructor: 'Aditya Bhardwaj',
    duration: '8 weeks',
    level: 'Advanced',
    price: 14999,
    image: '/api/placeholder/400/250',
    rating: 4.9,
    studentsCount: 3800,
    lessons: 35,
    tags: ['React', 'Hooks', 'Performance', 'State Management', 'Advanced'],
  },
  {
    id: 'nodejs-backend',
    title: 'Node.js Backend Development',
    description: 'Build scalable backend APIs with Node.js, Express, RESTful services, and database integration',
    category: 'web-dev',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Intermediate',
    price: 13999,
    image: '/api/placeholder/400/250',
    rating: 4.8,
    studentsCount: 2900,
    lessons: 38,
    tags: ['Node.js', 'Express', 'API', 'Backend', 'REST'],
  },
  {
    id: 'typescript-mastery',
    title: 'TypeScript Mastery',
    description: 'Master TypeScript for modern web development, type safety, and advanced patterns',
    category: 'web-dev',
    instructor: 'Aditya Bhardwaj',
    duration: '6 weeks',
    level: 'Intermediate',
    price: 9999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 2200,
    lessons: 25,
    tags: ['TypeScript', 'Type Safety', 'JavaScript', 'Advanced'],
  },
  {
    id: 'devops-aws',
    title: 'DevOps with AWS',
    description: 'CI/CD pipelines, infrastructure as code, monitoring, and DevOps best practices on AWS',
    category: 'devops',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Advanced',
    price: 19999,
    image: '/api/placeholder/400/250',
    rating: 4.8,
    studentsCount: 1600,
    lessons: 42,
    tags: ['DevOps', 'AWS', 'CI/CD', 'Infrastructure', 'Automation'],
  },
  {
    id: 'flutter-mobile',
    title: 'Flutter Mobile Development',
    description: 'Build beautiful cross-platform mobile apps with Flutter and Dart',
    category: 'mobile',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Intermediate',
    price: 16999,
    image: '/api/placeholder/400/250',
    rating: 4.6,
    studentsCount: 1400,
    lessons: 40,
    tags: ['Flutter', 'Dart', 'Mobile', 'Cross-platform'],
  },
  {
    id: 'python-automation',
    title: 'Python for Automation & Scripting',
    description: 'Learn Python for automation, web scraping, API development, and scripting',
    category: 'web-dev',
    instructor: 'Aditya Bhardwaj',
    duration: '8 weeks',
    level: 'Beginner',
    price: 8999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 3500,
    lessons: 30,
    tags: ['Python', 'Automation', 'Scripting', 'Web Scraping'],
  },
  {
    id: 'cybersecurity-fundamentals',
    title: 'Cybersecurity Fundamentals',
    description: 'Learn cybersecurity basics, network security, encryption, and security best practices',
    category: 'cybersecurity',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Beginner',
    price: 14999,
    image: '/api/placeholder/400/250',
    rating: 4.6,
    studentsCount: 1800,
    lessons: 38,
    tags: ['Cybersecurity', 'Network Security', 'Encryption', 'Security'],
  },
  {
    id: 'data-analytics',
    title: 'Data Analytics with SQL & Python',
    description: 'Master data analytics, SQL queries, data visualization, and business intelligence',
    category: 'data-science',
    instructor: 'Aditya Bhardwaj',
    duration: '8 weeks',
    level: 'Beginner',
    price: 11999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 2600,
    lessons: 32,
    tags: ['SQL', 'Python', 'Data Analytics', 'Business Intelligence'],
  },
  {
    id: 'gcp-cloud',
    title: 'Google Cloud Platform (GCP)',
    description: 'Master GCP services, cloud architecture, and prepare for GCP certification',
    category: 'cloud',
    instructor: 'Aditya Bhardwaj',
    duration: '8 weeks',
    level: 'Intermediate',
    price: 18999,
    image: '/api/placeholder/400/250',
    rating: 4.6,
    studentsCount: 1100,
    lessons: 35,
    tags: ['GCP', 'Google Cloud', 'Cloud', 'Infrastructure'],
  },
  {
    id: 'jenkins-cicd',
    title: 'CI/CD with Jenkins & GitLab',
    description: 'Master continuous integration and deployment with Jenkins, GitLab CI, and automation',
    category: 'devops',
    instructor: 'Aditya Bhardwaj',
    duration: '6 weeks',
    level: 'Intermediate',
    price: 12999,
    image: '/api/placeholder/400/250',
    rating: 4.7,
    studentsCount: 1300,
    lessons: 26,
    tags: ['Jenkins', 'CI/CD', 'GitLab', 'Automation', 'DevOps'],
  },
  {
    id: 'web3-defi',
    title: 'Web3 & DeFi Development',
    description: 'Build decentralized finance applications, smart contracts, and Web3 dApps',
    category: 'blockchain',
    instructor: 'Aditya Bhardwaj',
    duration: '10 weeks',
    level: 'Advanced',
    price: 22999,
    image: '/api/placeholder/400/250',
    rating: 4.8,
    studentsCount: 800,
    lessons: 42,
    tags: ['Web3', 'DeFi', 'Blockchain', 'Smart Contracts', 'dApps'],
  },
]

// Get tomorrow's date for all batch start dates
const tomorrowDate = getTomorrowDate()

export const batches: Batch[] = [
  {
    id: 'batch-001',
    courseId: 'nextjs-fullstack',
    name: 'Next.js 15 Full Stack - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Mon, Wed, Fri - 7:00 PM IST',
    capacity: 50,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-002',
    courseId: 'fullstack-mern',
    name: 'MERN Stack - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-05-02', // 12 weeks
    schedule: 'Tue, Thu - 6:00 PM IST',
    capacity: 40,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-003',
    courseId: 'ai-ml-python',
    name: 'AI & ML with Python - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-05-15', // 14 weeks
    schedule: 'Mon, Wed, Fri - 8:00 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-004',
    courseId: 'data-science-python',
    name: 'Data Science - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Sat, Sun - 10:00 AM IST',
    capacity: 35,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-005',
    courseId: 'aws-cloud',
    name: 'AWS Solutions Architect - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-05', // 8 weeks
    schedule: 'Mon, Wed, Fri - 7:30 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-006',
    courseId: 'docker-kubernetes',
    name: 'Docker & Kubernetes - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-03-22', // 6 weeks
    schedule: 'Tue, Thu - 7:00 PM IST',
    capacity: 35,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-007',
    courseId: 'react-native',
    name: 'React Native - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Mon, Wed, Fri - 6:30 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-008',
    courseId: 'ethical-hacking',
    name: 'Ethical Hacking - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-05-15', // 14 weeks
    schedule: 'Sat, Sun - 2:00 PM IST',
    capacity: 25,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-009',
    courseId: 'blockchain-web3',
    name: 'Blockchain & Web3 - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-05-02', // 12 weeks
    schedule: 'Tue, Thu - 8:00 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-010',
    courseId: 'react-advanced',
    name: 'Advanced React - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-05', // 8 weeks
    schedule: 'Mon, Wed, Fri - 6:00 PM IST',
    capacity: 40,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-011',
    courseId: 'azure-cloud',
    name: 'Microsoft Azure - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-05', // 8 weeks
    schedule: 'Tue, Thu - 7:00 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-012',
    courseId: 'nodejs-backend',
    name: 'Node.js Backend - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Mon, Wed, Fri - 6:30 PM IST',
    capacity: 40,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-013',
    courseId: 'typescript-mastery',
    name: 'TypeScript Mastery - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-03-22', // 6 weeks
    schedule: 'Sat, Sun - 11:00 AM IST',
    capacity: 35,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-014',
    courseId: 'devops-aws',
    name: 'DevOps with AWS - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Mon, Wed, Fri - 8:00 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-015',
    courseId: 'flutter-mobile',
    name: 'Flutter Mobile - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Tue, Thu - 7:30 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-016',
    courseId: 'python-automation',
    name: 'Python Automation - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-05', // 8 weeks
    schedule: 'Mon, Wed, Fri - 7:00 PM IST',
    capacity: 40,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-017',
    courseId: 'cybersecurity-fundamentals',
    name: 'Cybersecurity Fundamentals - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Sat, Sun - 1:00 PM IST',
    capacity: 35,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-018',
    courseId: 'data-analytics',
    name: 'Data Analytics - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-05', // 8 weeks
    schedule: 'Mon, Wed, Fri - 6:00 PM IST',
    capacity: 35,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-019',
    courseId: 'gcp-cloud',
    name: 'Google Cloud Platform - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-05', // 8 weeks
    schedule: 'Tue, Thu - 8:00 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-020',
    courseId: 'jenkins-cicd',
    name: 'CI/CD with Jenkins - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-03-22', // 6 weeks
    schedule: 'Sat, Sun - 10:00 AM IST',
    capacity: 35,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
  {
    id: 'batch-021',
    courseId: 'web3-defi',
    name: 'Web3 & DeFi - Batch 1',
    startDate: tomorrowDate,
    endDate: '2026-04-19', // 10 weeks
    schedule: 'Tue, Thu - 7:00 PM IST',
    capacity: 30,
    enrolled: 0,
    instructor: 'Aditya Bhardwaj',
    status: 'upcoming',
  },
]
// ============================================
// PRODUCTS - SOURCE CODE MARKETPLACE
// ============================================

export const productCategories: Category[] = [
  {
    id: 'it-software',
    name: 'IT/Software Development',
    description: 'Enterprise and SaaS applications',
    icon: '💻',
    color: 'from-blue-500 to-blue-600',
    courseCount: 1,
  },
  {
    id: 'edtech',
    name: 'EdTech/Online Education',
    description: 'Learning management systems',
    icon: '🎓',
    color: 'from-purple-500 to-purple-600',
    courseCount: 1,
  },
  {
    id: 'ecommerce',
    name: 'Ecommerce/Marketplace',
    description: 'Multi-vendor digital platforms',
    icon: '🛍️',
    color: 'from-pink-500 to-pink-600',
    courseCount: 1,
  },
  {
    id: 'recruitment',
    name: 'Online Recruitment',
    description: 'Job portals and hiring platforms',
    icon: '💼',
    color: 'from-green-500 to-green-600',
    courseCount: 1,
  },
  {
    id: 'information',
    name: 'Information Services',
    description: 'Directory and listing platforms',
    icon: '📋',
    color: 'from-yellow-500 to-yellow-600',
    courseCount: 1,
  },
  {
    id: 'media',
    name: 'Digital Media/Publishing',
    description: 'News portals and magazines',
    icon: '📰',
    color: 'from-red-500 to-red-600',
    courseCount: 1,
  },
  {
    id: 'charity',
    name: 'Social Services/Charity',
    description: 'Non-profit and charity platforms',
    icon: '❤️',
    color: 'from-rose-500 to-rose-600',
    courseCount: 1,
  },
  {
    id: 'fintech',
    name: 'FinTech/Retail Software',
    description: 'Payment and POS systems',
    icon: '💳',
    color: 'from-orange-500 to-orange-600',
    courseCount: 1,
  },
  {
    id: 'traveltech',
    name: 'TravelTech/Online Booking',
    description: 'Hotel and travel booking systems',
    icon: '✈️',
    color: 'from-cyan-500 to-cyan-600',
    courseCount: 1,
  },
  {
    id: 'foodtech',
    name: 'FoodTech/Online Delivery',
    description: 'Food ordering and delivery apps',
    icon: '🍕',
    color: 'from-amber-500 to-amber-600',
    courseCount: 1,
  },
]

export const products: Product[] = [
  {
    id: 'company-website',
    name: 'Company Website',
    description: 'Professional Next.js & Laravel full-stack company website with modern design, CMS, and analytics. Perfect for showcasing services and managing content.',
    resources: 'Next.js 14 + Laravel 11 - Modern Full-Stack Application',
    category: 'it-software',
    price: 4999,
    originalPrice: 9999,
    image: '/api/placeholder/400/250',
    icon: '💻',
    rating: 4.9,
    reviews: 245,
    downloads: 1200,
    tags: ['Next.js', 'Laravel 11', 'Full-Stack', 'Enterprise', 'CMS'],
    features: [
      'Responsive design with Tailwind CSS',
      'Admin panel with content management',
      'SEO optimization',
      'Email notifications',
      'Analytics dashboard',
      'Contact form integration',
      'Blog system',
      'Newsletter subscription',
    ],
    tech_stack: ['Next.js 14', 'React 18', 'Laravel 11', 'PostgreSQL', 'Tailwind CSS', 'TypeScript'],
    license: 'Commercial',
    deliveryFormat: 'source-code-with-docs',
    updateFrequency: 'Quarterly updates included',
    support: true,
    documentation: true,
    videoTutorials: true,
    sourceCodeAccess: true,
    lifetimeAccess: true,
    competitors: 'Google, Microsoft, Adobe, Salesforce, Oracle, Zoho',
  },
  {
    id: 'learning-management-marketplace',
    name: 'Learning Management Marketplace',
    description: 'Complete Learning Management System (LMS) with course creation, student management, assessments, and instructor tools. Laravel 11 powered.',
    resources: 'Laravel 11 - Complete Learning Management System',
    category: 'edtech',
    price: 5999,
    originalPrice: 11999,
    image: '/api/placeholder/400/250',
    icon: '🎓',
    rating: 4.8,
    reviews: 312,
    downloads: 1850,
    tags: ['Laravel 11', 'LMS', 'Education', 'Course Management', 'PHP'],
    features: [
      'Course creation and management',
      'Student enrollment system',
      'Assessment and quiz builder',
      'Progress tracking',
      'Certificate generation',
      'Discussion forums',
      'Live class integration',
      'Payment gateway integration',
      'Instructor dashboard',
      'Student dashboard',
      'Email notifications',
      'Batch management',
    ],
    tech_stack: ['Laravel 11', 'MySQL', 'Vue.js', 'Tailwind CSS', 'Stripe API', 'AWS S3'],
    license: 'Commercial',
    deliveryFormat: 'source-code-with-docs',
    updateFrequency: 'Monthly updates',
    support: true,
    documentation: true,
    videoTutorials: true,
    sourceCodeAccess: true,
    lifetimeAccess: true,
    competitors: 'Udemy, Coursera, edX, Skillshare, BYJU\'S, Unacademy, Vedantu',
  },
  {
    id: 'multi-vendor-digital-marketplace',
    name: 'Multi-Vendor Digital Marketplace',
    description: 'Enterprise-grade multi-vendor e-commerce platform. Supports hundreds of sellers with commission management, inventory, and order tracking.',
    resources: 'Laravel 11 - Multi-Vendor Digital Marketplace (2025)',
    category: 'ecommerce',
    price: 7999,
    originalPrice: 15999,
    image: '/api/placeholder/400/250',
    icon: '🛍️',
    rating: 4.9,
    reviews: 428,
    downloads: 2340,
    tags: ['Laravel 11', 'E-commerce', 'Marketplace', 'Multi-Vendor', 'PHP'],
    features: [
      'Vendor management system',
      'Product catalog with categories',
      'Shopping cart and checkout',
      'Order management',
      'Inventory tracking',
      'Commission management',
      'Payment gateway integration',
      'Shipping integration',
      'Review and rating system',
      'Seller dashboard',
      'Admin dashboard',
      'Mobile-friendly design',
      'Search and filtering',
      'Promotional tools',
    ],
    tech_stack: ['Laravel 11', 'MySQL', 'React', 'Tailwind CSS', 'Razorpay', 'Stripe', 'AWS S3'],
    license: 'Commercial',
    deliveryFormat: 'source-code-with-docs',
    updateFrequency: 'Bi-weekly updates',
    support: true,
    documentation: true,
    videoTutorials: true,
    sourceCodeAccess: true,
    lifetimeAccess: true,
    competitors: 'Amazon, Flipkart, Snapdeal, Meesho, JioMart, Nykaa',
  },
  {
    id: 'job-portal',
    name: 'Job Portal',
    description: 'Advanced job portal platform with employer management, job listings, applicant tracking, and candidate profiles. Build your recruitment ecosystem.',
    resources: 'Laravel 10 - Advanced Job Portal Website (2024)',
    category: 'recruitment',
    price: 4499,
    originalPrice: 8999,
    image: '/api/placeholder/400/250',
    icon: '💼',
    rating: 4.7,
    reviews: 189,
    downloads: 950,
    tags: ['Laravel 10', 'Job Portal', 'ATS', 'Recruitment', 'PHP'],
    features: [
      'Job posting system',
      'Employer dashboard',
      'Candidate profile management',
      'Application tracking',
      'Resume parsing',
      'Advanced search and filters',
      'Saved jobs functionality',
      'Email notifications',
      'Application status tracking',
      'Interview scheduling',
      'Admin dashboard',
      'Subscription plans',
    ],
    tech_stack: ['Laravel 10', 'MySQL', 'Vue.js', 'Tailwind CSS', 'Elasticsearch'],
    license: 'Commercial',
    deliveryFormat: 'source-code-with-docs',
    updateFrequency: 'Monthly updates',
    support: true,
    documentation: true,
    videoTutorials: true,
    sourceCodeAccess: true,
    lifetimeAccess: true,
    competitors: 'Indeed, Linkedin Jobs, Naukri.com, Shine.com, Internshala',
  },
  {
    id: 'directory-listing',
    name: 'Directory Listing Platform',
    description: 'Comprehensive business directory platform with advanced search, maps integration, and business verification. Perfect for local services.',
    resources: 'Laravel 10 - Directory Listing Website',
    category: 'information',
    price: 3999,
    originalPrice: 7999,
    image: '/api/placeholder/400/250',
    icon: '📋',
    rating: 4.6,
    reviews: 156,
    downloads: 780,
    tags: ['Laravel 10', 'Directory', 'Business Listing', 'Maps API', 'PHP'],
    features: [
      'Business listing management',
      'Advanced search and filters',
      'Maps integration',
      'Business verification',
      'Review and rating system',
      'Contact management',
      'Business hours',
      'Gallery uploads',
      'Subscription tiers',
      'Admin dashboard',
      'Featured listings',
      'Email notifications',
      'Analytics',
    ],
    tech_stack: ['Laravel 10', 'MySQL', 'Google Maps API', 'Vue.js', 'Bootstrap'],
    license: 'Commercial',
    deliveryFormat: 'source-code-with-docs',
    updateFrequency: 'Quarterly updates',
    support: true,
    documentation: true,
    videoTutorials: false,
    sourceCodeAccess: true,
    lifetimeAccess: true,
    competitors: 'Google Business, Yelp, Justdial, Sulekha, Yellow Pages India',
  },
  {
    id: 'news-portal',
    name: 'News Portal & Magazine',
    description: 'Modern news portal with multi-category support, author management, advanced SEO, and social media integration.',
    resources: 'Laravel 10 - News Portal and Magazine Website (2024)',
    category: 'media',
    price: 3499,
    originalPrice: 6999,
    image: '/api/placeholder/400/250',
    icon: '📰',
    rating: 4.7,
    reviews: 203,
    downloads: 1050,
    tags: ['Laravel 10', 'News Portal', 'CMS', 'Publishing', 'PHP'],
    features: [
      'Multi-category news management',
      'Author profiles',
      'Comment system',
      'Social sharing',
      'Email newsletter',
      'SEO optimization',
      'Viral content tracking',
      'Ad management',
      'Mobile app ready',
      'Push notifications',
      'Editor dashboard',
      'Advanced analytics',
      'Tag and category system',
    ],
    tech_stack: ['Laravel 10', 'MySQL', 'Vue.js', 'Tailwind CSS', 'Elasticsearch'],
    license: 'Commercial',
    deliveryFormat: 'source-code-with-docs',
    updateFrequency: 'Monthly updates',
    support: true,
    documentation: true,
    videoTutorials: true,
    sourceCodeAccess: true,
    lifetimeAccess: true,
    competitors: 'Times of India, The Hindu, BBC, NDTV, Indian Express',
  },
  {
    id: 'non-profit-charity',
    name: 'Non-Profit Charity Platform',
    description: 'Complete charity and non-profit management system with donation tracking, volunteer management, and campaign tools.',
    resources: 'Laravel 10 - Complete Non-Profit Charity Website',
    category: 'charity',
    price: 2999,
    originalPrice: 5999,
    image: '/api/placeholder/400/250',
    icon: '❤️',
    rating: 4.8,
    reviews: 134,
    downloads: 620,
    tags: ['Laravel 10', 'Charity', 'Non-Profit', 'Donations', 'PHP'],
    features: [
      'Donation management',
      'Campaign creation',
      'Volunteer management',
      'Donor profiles',
      'Email receipts',
      'Tax certificate generation',
      'Reports and analytics',
      'Payment gateway integration',
      'Newsletter system',
      'Social media integration',
      'Event management',
      'Testimonials',
    ],
    tech_stack: ['Laravel 10', 'MySQL', 'Vue.js', 'Bootstrap', 'Stripe', 'Razorpay'],
    license: 'Commercial',
    deliveryFormat: 'source-code-with-docs',
    updateFrequency: 'Quarterly updates',
    support: true,
    documentation: true,
    videoTutorials: false,
    sourceCodeAccess: true,
    lifetimeAccess: true,
    competitors: 'GiveIndia, Smile Foundation, CRY, Milaap, Ketto',
  },
  {
    id: 'point-of-sale-system',
    name: 'Point of Sale (POS) System',
    description: 'Complete POS solution with inventory management, sales tracking, and payment integration. Ideal for retail businesses.',
    resources: 'Laravel 9 - Advanced Complete Point of Sale Project',
    category: 'fintech',
    price: 4999,
    originalPrice: 9999,
    image: '/api/placeholder/400/250',
    icon: '💳',
    rating: 4.9,
    reviews: 267,
    downloads: 1420,
    tags: ['Laravel 9', 'POS', 'Retail', 'Inventory', 'PHP'],
    features: [
      'Product inventory management',
      'Point of sale interface',
      'Sales transactions',
      'Payment processing',
      'Barcode scanning',
      'Customer management',
      'Sales reports',
      'Staff management',
      'Multiple store support',
      'Offline mode',
      'Multi-currency support',
      'Tax calculations',
      'Receipt printing',
    ],
    tech_stack: ['Laravel 9', 'MySQL', 'Bootstrap', 'Stripe', 'Razorpay', 'jQuery'],
    license: 'Commercial',
    deliveryFormat: 'source-code-with-docs',
    updateFrequency: 'Monthly updates',
    support: true,
    documentation: true,
    videoTutorials: true,
    sourceCodeAccess: true,
    lifetimeAccess: true,
    competitors: 'Square, Shopify POS, Toast POS, Clover, PineLabs',
  },
  {
    id: 'hotel-booking-reservation',
    name: 'Hotel Booking & Reservation System',
    description: 'Complete hotel management system with room booking, guest management, invoicing, and payment integration.',
    resources: 'Laravel 10 - Hotel Booking Reservation System',
    category: 'traveltech',
    price: 5999,
    originalPrice: 11999,
    image: '/api/placeholder/400/250',
    icon: '✈️',
    rating: 4.8,
    reviews: 289,
    downloads: 1560,
    tags: ['Laravel 10', 'Hotel Booking', 'Travel Tech', 'Reservation', 'PHP'],
    features: [
      'Room inventory management',
      'Booking and reservation system',
      'Guest management',
      'Check-in/Check-out',
      'Housekeeping management',
      'Invoice generation',
      'Payment gateway integration',
      'Email confirmations',
      'Calendar view',
      'Multiple room types',
      'Pricing management',
      'Analytics dashboard',
      'Mobile-friendly interface',
    ],
    tech_stack: ['Laravel 10', 'MySQL', 'Vue.js', 'Tailwind CSS', 'Stripe', 'Razorpay'],
    license: 'Commercial',
    deliveryFormat: 'source-code-with-docs',
    updateFrequency: 'Bi-weekly updates',
    support: true,
    documentation: true,
    videoTutorials: true,
    sourceCodeAccess: true,
    lifetimeAccess: true,
    competitors: 'Booking.com, Expedia, MakeMyTrip, Oyo Rooms, FabHotels',
  },
  {
    id: 'multi-restaurant-food-ordering',
    name: 'Multi-Restaurant Food Ordering App',
    description: 'Complete food delivery platform supporting multiple restaurants with order tracking, delivery management, and payments.',
    resources: 'Laravel 11 - Multi-Restaurant Food Order Application',
    category: 'foodtech',
    price: 6999,
    originalPrice: 13999,
    image: '/api/placeholder/400/250',
    icon: '🍕',
    rating: 4.9,
    reviews: 356,
    downloads: 1890,
    tags: ['Laravel 11', 'Food Delivery', 'Multi-Restaurant', 'FoodTech', 'PHP'],
    features: [
      'Multi-restaurant management',
      'Menu management',
      'Real-time order tracking',
      'Delivery personnel tracking',
      'Payment gateway integration',
      'Rating and review system',
      'Customer wallet',
      'Promo codes and discounts',
      'Analytics dashboard',
      'Push notifications',
      'SMS integration',
      'Multiple cuisine filters',
      'Kitchen display system',
    ],
    tech_stack: ['Laravel 11', 'MySQL', 'Vue.js', 'Tailwind CSS', 'Google Maps API', 'Razorpay', 'Stripe'],
    license: 'Commercial',
    deliveryFormat: 'source-code-with-docs',
    updateFrequency: 'Weekly updates',
    support: true,
    documentation: true,
    videoTutorials: true,
    sourceCodeAccess: true,
    lifetimeAccess: true,
    competitors: 'Swiggy, Zomato, Uber Eats, Dunzo, Blinkit, Zepto',
  },
]